### ISSUE TITLE
doc error for running jms1/jms2 amqp samples

### ISSUE THREAD

**Issue by rfofuca** [SolaceSamples/solace-samples-amqp-qpid-jms2#22]
https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms1
and
https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms2

Running the Samples
To try individual samples, build the project from source and then run samples like the following:
./build/staged/bin/topicPublisher <msg_backbone_ip:port>

$ solace-samples-amqp-qpid-jms2-master]$ ./build/staged/bin/topicPublisher 192.168.133.44 default default
TopicPublisher is connecting to Solace router 192.168.133.44...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" javax.jms.JMSRuntimeException: No Provider scheme specified.

The instructions should include "amqp://":
./build/staged/bin/topicPublisher amqp://<msg_backbone_ip:port>

**Comment by Calo3003** [comment]
The error is still there... Any solution for fixing?

**Comment by aaron-613** [comment]
The issue has been addressed in both JMS1 and JMS2 sample repos.

> The instructions should include "amqp://":
> `./build/staged/bin/topicPublisher amqp://<msg_backbone_ip:port>`

This is done:
```
$ bin/topicPublisher
Usage: TopicPublisher amqp://<msg_backbone_ip:amqp_port> <username> <password>
```

@xcarlitos what was your issue?

**Comment by Mrc0113** [comment]
Closing this stale issue.
