### ISSUE TITLE
Improve this page link is broken.

### ISSUE THREAD

**Issue by PhilippeKhalife** [SolaceSamples/solace-samples-amqp-qpid-jms2#33]

**Comment by mdspielman** [comment]
Specifically on the tutorial pages like - https://dev.solace.com/samples/solace-samples-amqp-qpid-jms2/request-reply/

**Comment by Mrc0113** [comment]
Closing. "Improve this page" and other links have been fixed on the new tutorials site. automatic link checking is also in place.
