### ISSUE TITLE
Project clean up items for integration into Solace Dev Portal

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-amqp-qpid-jms2#6]
We should update the following items to improve ease of use in this project:

README should clearly mention the Qpid JMS API in the initial summary and project heading.
Contributing.md needs link cleanup now that project is moved.
README quick links to tutorials need a link update to reflect final project naming.
Contributors link in README needs a link update
NOTICE should be updated to only list 2017.
config.yml needs a small update to reflect final project naming.
Tutorials.yml needs a small update to include Qpid in the title.
All tutorials md files should mention Qpid in the following places:
-- opening summary paragraph
-- Goals section.
-- Closing paragraph
All coding samples should mention Qpid in the opening comment and in general when they mention AMQP specifically.

**Comment by mdspielman** [comment]
After merging the pull request, we should make sure the GitHub pages render properly as well: https://solacesamples.github.io/solace-samples-amqp-qpid-jms2/

**Comment by dfedorov-solace** [comment]
Well, the root of all the problems that the project URI was changed from "solace-samples-amqp-jms2" to "solace-samples-amqp-qpid-jms2" at the time of publishing to SolaceSamples and that broke its configuration (that was validated by me many times). Yes, I will repair it.
