### ISSUE TITLE
Build and run instructions for solace-samples-amqp-qpid-jms samples

### ISSUE THREAD

**Issue by rfofuca** [SolaceSamples/solace-samples-amqp-qpid-jms2#8]
Build instructions:
-	gradlew does not have exec file privileges
-	a “cd” step is missing
         $ git clone https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms2
        $ cd solace-samples-amqp-qpid-jms2/     <=================
        $ ./gradlew assemble
        bash: ./gradlew: Permission denied
        $ chmod +x gradlew <=================

Run instructions:
./build/staged/bin/topicPublisher <msg_backbone_ip:port>
The uri should be <amqp://msg_backbone_ip:port>

**Comment by mdspielman** [comment]
Fixed by PR. Closing.
